config/routes.rb
Rails.application.routes.draw do
  resources :statements

  root 'statements#index'

end

app/models/statement.rb
class Statement < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :set_statement, only: [:show, :edit, :update, :destroy]

  # GET /statements
  # GET /statements.json
  def index
    @statements = Statement.all.order(id: :desc)
  end

  # GET /statements/1
  # GET /statements/1.json
  def show
  end

  # GET /statements/new
  def new
    @statement = Statement.new
  end

  # GET /statements/1/edit
  def edit
  end

  # POST /statements
  # POST /statements.json
  def create
    @statement = Statement.new(statement_params)

    respond_to do |format|
      if @statement.save
        format.html { redirect_to statements_url, notice: 'Statement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @statement }
      else
        format.html { render action: 'new' }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statements/1
  # PATCH/PUT /statements/1.json
  def update
    respond_to do |format|
      if @statement.update(statement_params)
        format.html { redirect_to statements_url, notice: 'Statement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statements/1
  # DELETE /statements/1.json
  def destroy
    @statement.destroy
    respond_to do |format|
      format.html { redirect_to statements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statement
      @statement = Statement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statement_params
      params.require(:statement).permit(:content, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shiz Said in IT</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
    <center><h1>Shiz Said in IT</h1>
    <br/><br/><br/>
    <%= yield %>
    </center>
</div>


</body>
</html>

app/views/statements/_form.html.erb
<%= form_for(@statement) do |f| %>
  <% if @statement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statement.errors.count, "error") %> prohibited this statement from being saved:</h2>

      <ul>
      <% @statement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content, 'Enter the Shiz that was said' %><br>
    <%= f.text_area :content, :cols => "100", :rows => "10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statements/edit.html.erb
<h1>Editing the statement</h1>

<%= render 'form' %>

<%= link_to 'Show', @statement %> |
<%= link_to 'Back', statements_path %>

app/views/statements/index.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th align="center"><center>Statements</center></th>
    </tr>
  </thead>

  <tbody>
    <% @statements.each do |statement| %>
      <tr>
        <td><center><%= statement.content %></center></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Add a New Statement', new_statement_path %>

app/views/statements/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', statements_path %>

app/views/statements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @statement.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @statement.author %>
</p>

<%= link_to 'Edit', edit_statement_path(@statement) %> |
<%= link_to 'Back', statements_path %>